#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

// ---------------------------------------------------------
// Font Generator
// ---------------------------------------------------------

static void gen_font_size(stbtt_fontinfo *font, int font_size, int char_width, int char_height, const char *data_name, FILE *c_out) {
    float scale = stbtt_ScaleForPixelHeight(font, font_size);
    int ascent, descent, lineGap;
    stbtt_GetFontVMetrics(font, &ascent, &descent, &lineGap);
    ascent = ascent * scale;
    descent = descent * scale;

    fprintf(c_out, "const unsigned char ArkFontRobotoBold_%s[] = {\n        ", data_name);
    
    for (int i = 32; i < 127; i++) {
        int w, h, xoff, yoff;
        unsigned char *bitmap = stbtt_GetCodepointBitmap(font, 0, scale, i, &w, &h, &xoff, &yoff);
        
        // Output fixed char_width x char_height block
        int baseline_y = char_height * 0.8;
        
        for (int py = 0; py < char_height; py++) {
            for (int px = 0; px < char_width; px++) {
                int src_x = px - (char_width * 0.1) - xoff;
                int src_y = py - (baseline_y - ascent) - yoff;
                
                int val = 0;
                if (src_x >= 0 && src_x < w && src_y >= 0 && src_y < h) {
                    val = bitmap[src_y * w + src_x];
                }
                
                fprintf(c_out, "%d,", val);
            }
        }
        
        if (bitmap) stbtt_FreeBitmap(bitmap, NULL);
    }
    fprintf(c_out, "\n};\n");
}

void generate_fonts(void) {
    printf("  [Native Asset Gen] Generating fonts from TTF...\n");
    
    FILE *ttf = fopen("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", "rb");
    if (!ttf) {
        printf("WARNING: Could not open DejaVuSans-Bold.ttf\n");
        return;
    }
    
    fseek(ttf, 0, SEEK_END);
    size_t size = ftell(ttf);
    fseek(ttf, 0, SEEK_SET);
    
    unsigned char *ttf_buffer = malloc(size);
    fread(ttf_buffer, 1, size, ttf);
    fclose(ttf);
    
    stbtt_fontinfo font;
    if (!stbtt_InitFont(&font, ttf_buffer, stbtt_GetFontOffsetForIndex(ttf_buffer,0))) {
        printf("WARNING: Failed to init font\n");
        free(ttf_buffer);
        return;
    }
    
    FILE *c_out = fopen("arkrt/ArkGraphics/ArkFontRobotoBoldData.c", "w");
    if (!c_out) { free(ttf_buffer); return; }
    
    gen_font_size(&font, 28, 32, 36, "data", c_out);
    gen_font_size(&font, 56, 64, 72, "data2x", c_out);
    gen_font_size(&font, 84, 96, 108, "data3x", c_out);
    gen_font_size(&font, 112, 128, 144, "data4x", c_out);
    gen_font_size(&font, 168, 192, 216, "data6x", c_out);
    
    fclose(c_out);
    free(ttf_buffer);
    
    // Generate Swift file
    FILE *s_out = fopen("arkrt/ArkGraphics/ArkFontRobotoBold.swift", "w");
    if (!s_out) return;
    
    fprintf(s_out, 
        "// Auto-generated by aake font-gen\n"
        "@_silgen_name(\"ArkFontRobotoBold_data\") public var ArkFontRobotoBold_data_sym: UInt8\n"
        "@_silgen_name(\"ArkFontRobotoBold_data2x\") public var ArkFontRobotoBold_data2x_sym: UInt8\n"
        "@_silgen_name(\"ArkFontRobotoBold_data3x\") public var ArkFontRobotoBold_data3x_sym: UInt8\n"
        "@_silgen_name(\"ArkFontRobotoBold_data4x\") public var ArkFontRobotoBold_data4x_sym: UInt8\n"
        "@_silgen_name(\"ArkFontRobotoBold_data6x\") public var ArkFontRobotoBold_data6x_sym: UInt8\n\n"
        "public struct ArkFontRobotoBold {\n"
        "    public static let charWidth = 32\n"
        "    public static let charHeight = 36\n"
        "    public static let charWidth2x = 64\n"
        "    public static let charHeight2x = 72\n"
        "    public static let charWidth3x = 96\n"
        "    public static let charHeight3x = 108\n"
        "    public static let charWidth4x = 128\n"
        "    public static let charHeight4x = 144\n"
        "    public static let charWidth6x = 192\n"
        "    public static let charHeight6x = 216\n\n"
        "    public static var data: UnsafePointer<UInt8> { return withUnsafePointer(to: &ArkFontRobotoBold_data_sym) { $0 } }\n"
        "    public static var data2x: UnsafePointer<UInt8> { return withUnsafePointer(to: &ArkFontRobotoBold_data2x_sym) { $0 } }\n"
        "    public static var data3x: UnsafePointer<UInt8> { return withUnsafePointer(to: &ArkFontRobotoBold_data3x_sym) { $0 } }\n"
        "    public static var data4x: UnsafePointer<UInt8> { return withUnsafePointer(to: &ArkFontRobotoBold_data4x_sym) { $0 } }\n"
        "    public static var data6x: UnsafePointer<UInt8> { return withUnsafePointer(to: &ArkFontRobotoBold_data6x_sym) { $0 } }\n"
        "}\n"
    );
    fclose(s_out);
    
    printf("  [Native Asset Gen] Fonts generated successfully.\n");
}

// ---------------------------------------------------------
// Cursor Generator
// ---------------------------------------------------------

#pragma pack(push, 1)
struct CURHeader {
    uint16_t zero;
    uint16_t type;
    uint16_t count;
    uint8_t width;
    uint8_t height;
    uint8_t colors;
    uint8_t res;
    uint16_t hot_x;
    uint16_t hot_y;
    uint32_t size;
    uint32_t offset;
};
struct DIBHeader {
    uint32_t dib_size;
    int32_t width;
    int32_t height;
    uint16_t planes;
    uint16_t bpp;
    uint32_t comp;
    uint32_t img_size;
};
#pragma pack(pop)

void generate_cursors(void) {
    printf("  [Native Asset Gen] Generating cursors from .cur...\n");
    
    const char *cur_path = "assets/cursor.cur";
    FILE *f = fopen(cur_path, "rb");
    if (!f) {
        system("unzip -o arkrt/ArkGraphics/mousecursorpack.zip -d /tmp/ >/dev/null 2>&1");
        cur_path = "/tmp/cursor.cur"; // Adjust based on actual zip contents
        f = fopen(cur_path, "rb");
        if (!f) return;
    }
    
    fseek(f, 0, SEEK_END);
    size_t sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    
    uint8_t *data = malloc(sz);
    fread(data, 1, sz, f);
    fclose(f);
    
    struct CURHeader *hdr = (struct CURHeader *)data;
    if (hdr->type != 2) {
        printf("ERROR: Not a CUR file\n");
        free(data);
        return;
    }
    
    struct DIBHeader *dib = (struct DIBHeader *)(data + hdr->offset);
    int w = dib->width;
    int h = dib->height / 2;
    
    if (dib->bpp != 32) {
        printf("ERROR: Only 32bpp cursors supported\n");
        free(data);
        return;
    }
    
    uint8_t *pixels = data + hdr->offset + dib->dib_size;
    
    FILE *out = fopen("arkrt/ArkGraphics/ArkCursor.swift", "w");
    if (!out) { free(data); return; }
    
    fprintf(out, "// Auto-generated by aake cursor-gen\n");
    fprintf(out, "let cursorWidth = %d\n", w);
    fprintf(out, "let cursorHeight = %d\n", h);
    fprintf(out, "let cursorHotX = %d\n", hdr->hot_x);
    fprintf(out, "let cursorHotY = %d\n", hdr->hot_y);
    fprintf(out, "let cursorData: [UInt32] = [\n");
    
    for (int i = h - 1; i >= 0; i--) {
        uint8_t *row = pixels + (i * w * 4);
        for (int j = 0; j < w; j++) {
            uint8_t b = row[j*4 + 0];
            uint8_t g = row[j*4 + 1];
            uint8_t r = row[j*4 + 2];
            uint8_t a = row[j*4 + 3];
            uint32_t pixel = (a << 24) | (r << 16) | (g << 8) | b;
            fprintf(out, "0x%08X, ", pixel);
        }
        fprintf(out, "\n");
    }
    
    fprintf(out, "]\n");
    fclose(out);
    free(data);
    
    printf("  [Native Asset Gen] Cursors generated successfully.\n");
}
